baseURL = "https://graphgp.com/"
enableGitInfo = false                     # retrieve last modified date from git commits
enableRobotsTXT = true                    # /robots.txt
googleAnalytics = ""                      # google analytics id
hasCJKLanguage = true                     # Chinese/Japanese/Korean
languageCode = "en"                       # content language
paginate = 5                              # number of posts each page
rssLimit = 10                             # maximum items in rss feeds
theme = "hugo-theme-texify"               # theme directory name
title = "Graph-based Genetic Programming Workshop" # website title

[author]
email = "d9w@pm.me" # your email
name = "Dennis Wilson"          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "home" # section id
name = "Home"       # section display title
url = "/"           # path to the section
weight = 1          # order of sections
[[menu.main]]
identifier = "cfp"
name = "Call for Papers"
url = "/cfp/"
weight = 2
[[menu.main]]
identifier = "program"
name = "Program"
url = "/program/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

# https://gohugo.io/content-management/taxonomies#configure-taxonomies
[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "Graph-based Genetic Programming Workshop" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = "" # notes in the website footer
keywords = ["hugo", "latex", "theme"] # website keywords

customCSS = []            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
emphasisWithDots = true   # use dots to emphasize chinese texts, see https://zh.wikipedia.org/wiki/%E7%9D%80%E9%87%8D%E5%8F%B7
since = "2022"            # website created year
toc = false               # whether to enable table of contents in posts

